---
roles:
  - name: cchurch.admin-users
    version: 0.8.6
  - name: geerlingguy.certbot
    version: 4.2.0
  - name: geerlingguy.firewall
    version: 2.5.0
  - name: geerlingguy.mysql
    version: 3.3.2
  - name: geerlingguy.nodejs
    version: 6.0.0
  - name: geerlingguy.postgresql
    version: 3.1.1
  - name: geerlingguy.redis
    version: 1.7.0
  - name: geerlingguy.security
    version: 2.0.1
  - name: geerlingguy.swap
    version: 1.0.2
  - name: manala.motd
    version: 2.0.7
  - name: manala.ntp
    version: 2.0.1
  - name: manala.sudo
    version: 2.0.6
  - name: manala.timezone
    version: 2.0.2
  - name: manala.vim
    version: 2.0.1
  - name: ocha.yarn
    version: v1.2.1
  - name: stouts.hostname
    version: 1.1.0
  - name: ypsman.resolv
  - role: zzet.rbenv
    version: 3.5.0

collections:
  - name: community.general
    version: 4.0.1
  - name: nginxinc.nginx_core
    version: 0.4.0