- hosts: all
  become: true
  tags: basic
  vars:
    swap_file_size_mb: "{{ 2048 if ansible_memtotal_mb > 2048 else ansible_memtotal_mb }}"
  pre_tasks:

    - name: Update cache repo
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags:
        - apt

    - name: Upgrade all apt packages
      apt:
        upgrade: dist
      tags:
       - apt
       - upgrade

    - name: Set authorized key took from file
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    - name: Install basic packages
      apt:
        name: "{{ item }}"
      loop: "{{common_playbook_basic_packages}}"

    - name: Ensure a locale en_US.UTF-8 exists
      locale_gen:
        name: en_US.UTF-8
        state: present

    - name: Setting swap
      include_role:
        name: geerlingguy.swap
      tags:
        - swap

    - name: Setting timezone
      include_role:
        name: manala.timezone
      vars:
        manala_timezone_default: "{{ common_playbook_timezone }}"
      tags:
        - timezone

    - name: Setting ntp servers
      group:
        name: manala.ntp
      tags:
        - ntp

    - name: Setting ssh login message
      include_role:
        name: manala.motd
      vars:
        manala_motd_template: template/cow.j2
        manala_motd_message:  muuuuuuuuuuuuuuh
      tags:
        - ssh

    - name: Setting vim
      include_role:
        name: manala.vim
      vars:
        manala_vim_config_template: config/empty.j2
        manala_vim_config:
          - '"## General'
          - 'set encoding=utf8'
          - 'set number	"# Show line numbers'
          - 'set linebreak	"# Break lines at word (requires Wrap lines)'
          - 'set showbreak=+++	"# Wrap-broken line prefix'
          - 'set textwidth=100	"# Line wrap (number of cols)'
          - 'set showmatch	"# Highlight matching brace'
          - 'set visualbell	"# Use visual bell (no beeping)'
          - 'set hlsearch	"# Highlight all search results'
          - 'set smartcase	"# Enable smart-case search'
          - 'set ignorecase	"# Always case-insensitive'
          - 'set incsearch	"# Searches for strings incrementally'
          - 'set autoindent	"# Auto-indent new lines'
          - 'set expandtab	"# Use spaces instead of tabs'
          - 'set shiftwidth=2	"# Number of auto-indent spaces'
          - 'set smartindent	"# Enable smart-indent'
          - 'set smarttab	"# Enable smart-tabs'
          - 'set softtabstop=2	"# Number of spaces per Tab'
      tags:
        - vim

    - name: Set hostname
      include_role:
        name: stouts.hostname
      vars:
        hostname_enabled: yes
        hostname_hostname: "{{inventory_hostname}}"
        hostname_hostname_short: "{{hostname_hostname.split('.')[:-1]|join('.')}}"
      tags:
        - hostname

    - name: Setting dns servers
      include_role:
        name: ypsman.resolv
      vars:
        resolv_dns_domain: ''
        resolv_dns_server: "{{ common_playbook_dns_servers }}"
        resolv_searchpath: []
      tags:
        - dns

    - name: Setting firewall rules
      include_role:
        name: geerlingguy.firewall
      vars:
        firewall_allowed_tcp_ports: "{{ common_playbook_firewall_tcp_ports }}"
      tags:
        - firewall

    - name: Creating admin group
      group:
        name: admin
      tags:
        - users

    - name: Setting sudo for admin group
      include_role:
        name: manala.sudo
      vars:
        manala_sudo_sudoers:
          - file: admin
            config:
              - '%admin': ALL=NOPASSWD:ALL
      tags:
        - sudo
        - users

    - name: Creating Admin Users
      user:
        name: "{{ item.name }}"
        shell: /bin/bash
        groups: admin
      loop: "{{ common_playbook_admin_users }}"
      tags:
        - users

    - name: Adding authorized keys for admins
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ item.authorized_key }}"
      loop: "{{ common_playbook_admin_users }}"
      tags:
        - users

    - name: Setting ssh, autoupdate and fail2ban
      include_role:
        name: geerlingguy.security
      vars:
        security_ssh_port: "{{ common_playbook_ssh_port }}"
        security_ssh_password_authentication: "no"
        security_ssh_permit_root_login: "without-password"
        security_autoupdate_reboot: "true"
        security_autoupdate_reboot_time: "10:00"
        security_autoupdate_mail_to: "{{common_playbook_autoupdate_email_address}}"
        security_autoupdate_mail_on_error: true
      tags:
        - ssh
        - updates
        - firewall