- name: General server setup (apt, sudo, admins, ssh, firewall, etc..)
  import_playbook: common.yml
  tags:
    - basic
    - bootstrap

- hosts: all
  become: true
  tags:
    - mysql
  tasks:
    - name: Installing mysql server
      include_role:
        name: geerlingguy.mysql
