- name: General server setup (apt, sudo, admins, ssh, firewall, etc..)
  import_playbook: common.yml

- hosts: mysql
  become: true
  tags:
    - mysql
  tasks:
    - name: Installing mysql server
      include_role:
        name: geerlingguy.mysql
